"""Build SKILLS_INDEX.md by reconciling installed skills against demonstration docs.

Source of truth is the filesystem, not any agent's claim: a skill counts as
demonstrated only if a doc exists under crisp_dm/*/ named after it AND that doc
has YAML frontmatter naming the skill.
"""
import json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SKILLS = ROOT / ".claude" / "skills"
ML_PACK = "param087/agent-ml-skills"
AN_PACK = "nimrodfisher/data-analytics-skills"

# 15 skills installed from the ML pack; everything else came from the analytics pack.
ML_SKILLS = {
    "data-cleaning", "experiment-tracking", "exploratory-data-analysis",
    "feature-engineering", "hyperparameter-tuning", "imbalanced-data",
    "llm-finetuning", "ml-debugging", "model-evaluation", "model-serving",
    "pandas-patterns", "pytorch-training-loop", "rag-pipeline",
    "reproducible-ml", "sklearn-pipelines",
}
PHASES = {
    "01_business_understanding": "1 — Business Understanding",
    "02_data_understanding":     "2 — Data Understanding",
    "03_data_preparation":       "3 — Data Preparation",
    "04_modeling":               "4 — Modeling",
    "05_evaluation":             "5 — Evaluation",
    "06_deployment":             "6 — Deployment",
}

installed = sorted(p.name for p in SKILLS.iterdir() if (p / "SKILL.md").is_file())

def frontmatter(path):
    txt = path.read_text(errors="replace")
    m = re.match(r"^---\n(.*?)\n---\n", txt, re.S)
    if not m:
        return {}
    out = {}
    for line in m.group(1).splitlines():
        if ":" in line and not line.startswith((" ", "-")):
            k, v = line.split(":", 1)
            out[k.strip()] = v.strip()
    return out

found = {}
for phase_dir, phase_label in PHASES.items():
    d = ROOT / "crisp_dm" / phase_dir
    if not d.is_dir():
        continue
    for doc in sorted(d.glob("*.md")):
        fm = frontmatter(doc)
        name = fm.get("skill") or doc.stem
        found.setdefault(name, []).append((phase_label, doc.relative_to(ROOT), bool(fm)))

rows, missing = [], []
for s in installed:
    pack = ML_PACK if s in ML_SKILLS else AN_PACK
    if s in found:
        phase, doc, has_fm = found[s][0]
        rows.append((s, pack, phase, str(doc), "yes" if has_fm else "no frontmatter"))
    else:
        rows.append((s, pack, "—", "—", "MISSING"))
        missing.append(s)

orphans = sorted(set(found) - set(installed))
n_ml = sum(1 for s in installed if s in ML_SKILLS)

lines = [
    "# Skills Coverage Index",
    "",
    f"**{len(installed)} skills installed** — {n_ml} from `{ML_PACK}`, "
    f"{len(installed)-n_ml} from `{AN_PACK}`.",
    f"**{len(installed)-len(missing)} demonstrated** on the Kaggle Telco Customer Churn dataset, "
    f"mapped to CRISP-DM phases.",
    "",
    "This table is generated by `src/build_skills_index.py`, which reconciles the installed",
    "skill directories against the demonstration documents actually present on disk — so a",
    "skill only shows as covered if its document exists.",
    "",
    "| # | Skill | Pack | CRISP-DM phase | Demonstration doc | Covered |",
    "|---:|---|---|---|---|:--:|",
]
for i, (s, pack, phase, doc, cov) in enumerate(rows, 1):
    short = "ml-skills" if pack == ML_PACK else "analytics-skills"
    link = f"[{doc}]({doc})" if doc != "—" else "—"
    mark = "✅" if cov == "yes" else ("⚠️" if cov == "no frontmatter" else "❌")
    lines += [f"| {i} | `{s}` | {short} | {phase} | {link} | {mark} |"]

lines += ["", "## Reconciliation", ""]
lines += [f"- Installed skills: **{len(installed)}**",
          f"- Demonstrated: **{len(installed)-len(missing)}**",
          f"- Missing: **{len(missing)}**" + (f" — {', '.join(missing)}" if missing else " — none")]
if orphans:
    lines += [f"- Docs with no matching installed skill: {', '.join(orphans)}"]
lines += ["",
    "### Name-collision note",
    "",
    "The analytics pack ships two *different* skills that share a `name:` with another skill in",
    "a different category. Installing naively would have let one silently overwrite the other,",
    "so both were kept and the second was renamed on install:",
    "",
    "| Original path | Installed as |",
    "|---|---|",
    "| `01-data-quality-validation/schema-mapper` | `schema-mapper` (DB/ERD understanding) |",
    "| `02-documentation-knowledge/schema-mapper` | `schema-mapper-mapping` (source→target column mapping) |",
    "| `01-data-quality-validation/metric-reconciliation` | `metric-reconciliation` (cross-source validation) |",
    "| `02-documentation-knowledge/metric-reconciliation` | `metric-reconciliation-tracing` (discrepancy tracing) |",
]
(ROOT / "SKILLS_INDEX.md").write_text("\n".join(lines) + "\n")
print(f"installed={len(installed)} demonstrated={len(installed)-len(missing)} missing={len(missing)}")
if missing:
    print("  still missing:", ", ".join(missing))
