"""
Tier 1-4 Tests for React Data Science Dashboard Build & Render (F11-F14).
Verifies package scaffolding, data integrations, production build cleanliness,
and executes programmatic component render tests.
"""

import json
import os
import shutil
import subprocess
from pathlib import Path
import pytest


class TestDashboardE2E:
    """Comprehensive test suite for the React Admin Dashboard frontend."""

    def test_t1_dashboard_directory_and_package_json(self, dashboard_dir: Path):
        """[F11] Verifies dashboard/package.json exists with required scripts and dependencies."""
        pkg_json_path = dashboard_dir / "package.json"
        if not pkg_json_path.exists():
            pytest.skip("dashboard/package.json does not exist yet.")

        with open(pkg_json_path, "r", encoding="utf-8") as f:
            pkg = json.load(f)

        scripts = pkg.get("scripts", {})
        assert "build" in scripts, "package.json missing 'build' script"
        assert "test" in scripts or "test:run" in scripts, "package.json missing 'test' script"

        deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
        assert "react" in deps, "package.json missing react dependency"

    def test_t1_dashboard_components_structure(self, dashboard_dir: Path):
        """[F12] Verifies expected dashboard component files are present in dashboard/src/components."""
        components_dir = dashboard_dir / "src" / "components"
        if not components_dir.exists():
            pytest.skip("dashboard/src/components directory does not exist yet.")

        files = [f.name for f in components_dir.glob("*.tsx")]
        assert len(files) >= 3, f"Expected at least 3 UI components in dashboard/src/components, found {files}"

    def test_t1_dashboard_data_integration_files(self, dashboard_dir: Path):
        """[F13] Verifies data assets exist in public/data or default fallback data is provided."""
        public_data_json = dashboard_dir / "public" / "data" / "pipeline_output.json"
        fallback_data = dashboard_dir / "src" / "data" / "defaultData.ts"

        has_data = public_data_json.exists() or fallback_data.exists()
        if not has_data:
            pytest.skip("Neither public/data/pipeline_output.json nor fallback defaultData.ts found yet.")

        assert has_data, "Dashboard must have either public pipeline output or default fallback data"

    def test_t4_dashboard_npm_build(self, dashboard_dir: Path):
        """[F14] Executes `npm run build` in dashboard/ and verifies exit code 0."""
        pkg_json_path = dashboard_dir / "package.json"
        if not pkg_json_path.exists():
            pytest.skip("dashboard/package.json not yet created.")

        node_modules = dashboard_dir / "node_modules"
        if not node_modules.exists():
            # If node_modules does not exist, run npm install
            install_proc = subprocess.run(
                ["npm", "install"],
                cwd=str(dashboard_dir),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                timeout=180,
            )
            if install_proc.returncode != 0:
                pytest.fail(f"npm install failed in dashboard:\n{install_proc.stderr}")

        build_proc = subprocess.run(
            ["npm", "run", "build"],
            cwd=str(dashboard_dir),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=180,
        )

        assert build_proc.returncode == 0, (
            f"npm run build failed with exit code {build_proc.returncode}.\nStderr: {build_proc.stderr}\nStdout: {build_proc.stdout}"
        )

        dist_index = dashboard_dir / "dist" / "index.html"
        assert dist_index.exists(), "dashboard/dist/index.html was not generated by npm run build"

    def test_t4_dashboard_programmatic_render_tests(self, dashboard_dir: Path):
        """[F14] Executes `npm test` or `npx vitest run` and verifies all component render tests pass."""
        pkg_json_path = dashboard_dir / "package.json"
        if not pkg_json_path.exists():
            pytest.skip("dashboard/package.json not yet created.")

        test_proc = subprocess.run(
            ["npm", "test"],
            cwd=str(dashboard_dir),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=120,
        )

        # In case npm test runs in watch mode or script is different, fallback to vitest run if needed
        if test_proc.returncode != 0 and "watch" in test_proc.stderr.lower():
            test_proc = subprocess.run(
                ["npx", "vitest", "run"],
                cwd=str(dashboard_dir),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                timeout=120,
            )

        assert test_proc.returncode == 0, (
            f"Dashboard programmatic tests failed.\nStderr: {test_proc.stderr}\nStdout: {test_proc.stdout}"
        )
